#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: $0 <hostname>"
  exit 1
fi

HOSTNAME=$1
mkdir -p /root/oct24-certs/${HOSTNAME}

openssl req -new -sha256 -newkey rsa:4096 -nodes \
  -keyout /root/oct24-certs/${HOSTNAME}/${HOSTNAME}.key \
  -out /root/oct24-certs/${HOSTNAME}/${HOSTNAME}.csr \
  -config <(
cat <<EOF
[ req ]
default_bits = 4096
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C = US
ST = FL
L = TAMPA
O = Citigroup Inc.
OU = 165345
CN = ${HOSTNAME}

[ req_ext ]
subjectAltName = @alt_names
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth

[ alt_names ]
DNS.1 = ${HOSTNAME}
DNS.2 = *.cde-k4sg67rt.apps.mlab-ctigtdcai03d.ecs.dyn.nsroot.net
DNS.3 = cde-k4sg67rt.apps.mlab-ctigtdcai03d.ecs.dyn.nsroot.net
DNS.4 = *.apps.mlab-ctigtdcai03d.ecs.dyn.nsroot.net
DNS.5 = apps.mlab-ctigtdcai03d.ecs.dyn.nsroot.net
EOF
)
